name: Run Gamblor Script

on:
  schedule:
    - cron: '*/1 * * * *'   # Runs every 5 minutes
  workflow_dispatch:         # Still lets you run it manually if needed

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python script
        run: python update_scores_local.py
